### ISSUE TITLE
Correciones: Kitten

### ISSUE THREAD

**Issue by ghost** [Lizbethperez/Ejercicio-Kitten#1]
Hola Liz, te dejo aquí correciones a tu proyecto 😄 
A mejorar: No olvides hacer la configuracion del box-sizing para el body y solo el body, esta propiedad se hereda, si no se hace, se genera este espacio en blanco en los bordes del navegador que finalmente provoca un scroll no deseado. Prueba mejorando tu css con estas propiedades 
``` css
 body{
   box-sizing:border-box;
   padding:0;
   margin:0;
 }
``` 
Invertiste el orden de los gatos para la version de tablet y de mobile (mb = gato dormido, tblt = atardecer), sin embargo esto no afecta tu puntuación pero si es importante mejorar la atención al detalle

Puntuacion: **196.40/200**
